trigger: none

pr: none

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git switch -c version-bump
  displayName: Switch to new branch

- script: |
    git config user.email "alex.gorischek@gmail.com"
    git config user.name "Alex Gorischek via Azure Pipeline"
  displayName: Set Git config

- script: |
    npm version patch
  displayName: 'Bump version'

- task: CreatePullRequest@1
  inputs:
    repoType: 'GitHub'
    githubEndpoint: 'agorischek'
    githubRepository: '$(Build.Repository.Name)'
    sourceBranch: 'version-bump'
    targetBranch: 'master'
    title: 'Bump version after autorelease'
    description: 'Bump version after autorelease'
    passPullRequestIdBackToADO: true

# - script: |
#     git config user.email "alex.gorischek@gmail.com"
#     git config user.name "Alex Gorischek via Azure Pipeline"
#     git commit -m "Bump version"
#   displayName: Commit version

# - script: |
#     git show-ref
#     git push origin master
#   displayName: Git push
