trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm version patch
  displayName: 'Bump version'

- script: |
    git config user.email "alex.gorischek@gmail.com"
    git config user.name "Alex Gorischek via Azure Pipeline"
    git commit -m "Bump version"
  displayName: Commit version

- script: |
    git push origin master
  displayName: Git push
